// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpJ3oTyT-CSD1n0h0o_Z0PHzmYWy4Bgk',
    appId: '1:558287911723:web:d3d01635dd443702dc636e',
    messagingSenderId: '558287911723',
    projectId: 'quirk-408521',
    authDomain: 'quirk-408521.firebaseapp.com',
    storageBucket: 'quirk-408521.appspot.com',
    measurementId: 'G-HLMBLFHLW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXycPYhAsZ5iu3f11Iqn7Lrls7TJcB640',
    appId: '1:558287911723:android:c33bc691be1be9bfdc636e',
    messagingSenderId: '558287911723',
    projectId: 'quirk-408521',
    storageBucket: 'quirk-408521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1qsRfFMvPsqv6z7RMjhD9DYPoM1ASRI',
    appId: '1:558287911723:ios:dfa9139f58cadbbfdc636e',
    messagingSenderId: '558287911723',
    projectId: 'quirk-408521',
    storageBucket: 'quirk-408521.appspot.com',
    iosBundleId: 'com.example.quirkApp',
  );
}
